name: NetThud - Update Live Feed

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes (GitHub minimum)

permissions:
  contents: write

concurrency:
  group: netthud-update-live
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate live.json
        env:
          # Optional: if you later add a real live-score API key, put it in repo secrets as LIVESCORE_API_KEY
          LIVESCORE_API_KEY: ${{ secrets.LIVESCORE_API_KEY }}
        run: node scripts/generate-live.mjs

      - name: Commit & push if changed
        run: |
          git config user.name "netthud-bot"
          git config user.email "netthud-bot@users.noreply.github.com"
          git add live.json
          git diff --cached --quiet || (git commit -m "Update live.json" && git push)