name: NetThud - Update AI News

on:
  workflow_dispatch:
  schedule:
    - cron: "12 * * * *"

permissions:
  contents: write

concurrency:
  group: netthud-update-news
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate ai-news.json
        run: node scripts/generate-news.mjs

      - name: Commit & push if changed
        run: |
          git config user.name "netthud-bot"
          git config user.email "netthud-bot@users.noreply.github.com"
          git add assets/data/ai-news.json
          git diff --cached --quiet || (git commit -m "Update ai-news.json" && git push)