name: NetThud - Update Upcoming

on:
  workflow_dispatch:
  schedule:
    - cron: "17 * * * *"

permissions:
  contents: write

concurrency:
  group: netthud-update-upcoming
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate upcoming.json
        env:
          FOOTBALL_DATA_TOKEN: ${{ secrets.FOOTBALL_DATA_TOKEN }}
        run: node scripts/generate-upcoming.mjs

      - name: Commit & push if changed
        run: |
          git config user.name "netthud-bot"
          git config user.email "netthud-bot@users.noreply.github.com"
          git add assets/data/upcoming.json
          git diff --cached --quiet || (git commit -m "Update upcoming.json" && git push)
